const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
const db = {};
db.mongoose = mongoose;
db.user = require("./user");
db.role = require("./role");
db.token = require("./token");
db.ROLES = ["user", "admin", "team", "verified"];
module.exports = db;